export const ConfigFields = [
  {
    type: "static-text",
    id: "info",
    width: 12,
    label: "Warning",
    value:
      "Please be aware, that the AWS credentials will be stored in plain text and are available to everyone accessing this computer. Make sure to use a dedicated IAM user with the least amount of privileges.",
  },
  {
    type: "textinput",
    id: "accessKeyId",
    label: "Access Key ID",
    tooltip:
      "Enter the Access Key ID you've created for the Companion user in the IAM.",
    width: 12,
  },
  {
    type: "textinput",
    id: "secretAccessKey",
    label: "Secret Access Key",
    tooltip:
      "Enter the Secret Access Key you've created for the Companion user in the IAM.",
    width: 12,
  },
  {
    type: "dropdown",
    id: "region",
    label: "AWS Region",
    tooltip: "Select the AWS Region in which your EC2 instances are deployed",
    width: 8,
    choices: [
      { id: "us-east-1", label: "US East (N. Virginia)" },
      { id: "us-east-2", label: "US East (Ohio)" },
      { id: "us-west-1", label: "US West (N. California)" },
      { id: "us-west-2", label: "US West (Oregon)" },
      { id: "af-south-1", label: "Africa (Cape Town)" },
      { id: "ap-east-1", label: "Asia Pacific (Hong Kong)" },
      { id: "ap-south-2", label: "Asia Pacific (Hyderabad)" },
      { id: "ap-southeast-3", label: "Asia Pacific (Jakarta)" },
      { id: "ap-southeast-5", label: "Asia Pacific (Malaysia)" },
      { id: "ap-southeast-4", label: "Asia Pacific (Melbourne)" },
      { id: "ap-south-1", label: "Asia Pacific (Mumbai)" },
      { id: "ap-northeast-3", label: "Asia Pacific (Osaka)" },
      { id: "ap-northeast-2", label: "Asia Pacific (Seoul)" },
      { id: "ap-southeast-1", label: "Asia Pacific (Singapore)" },
      { id: "ap-southeast-2", label: "Asia Pacific (Sydney)" },
      { id: "ap-southeast-7", label: "Asia Pacific (Thailand)" },
      { id: "ap-northeast-1", label: "Asia Pacific (Tokyo)" },
      { id: "ca-central-1", label: "Canada (Central)" },
      { id: "ca-west-1", label: "Canada (Calgary)" },
      { id: "cn-north-1", label: "China (Beijing)" },
      { id: "cn-northwest-1", label: "China (Ningxia)" },
      { id: "eu-central-1", label: "Europe (Frankfurt)" },
      { id: "eu-west-1", label: "Europe (Ireland)" },
      { id: "eu-west-2", label: "Europe (London)" },
      { id: "eu-south-1", label: "Europe (Milan)" },
      { id: "eu-west-3", label: "Europe (Paris)" },
      { id: "eu-south-2", label: "Europe (Spain)" },
      { id: "eu-north-1", label: "Europe (Stockholm)" },
      { id: "eu-central-2", label: "Europe (Zurich)" },
      { id: "il-central-1", label: "Isreal (Tel Aviv)" },
      { id: "mx-central-1", label: "Mexico (Central)" },
      { id: "me-south-1", label: "Middle East (Bahrain)" },
      { id: "me-central-1", label: "Middle East (UAE)" },
      { id: "sa-east-1", label: "South America (São Paulo)" },
    ],
    default: "eu-central-1",
  },
  {
    type: "number",
    id: "pollingInterval",
    label: "Polling Interval",
    tooltip:
      "Configure how often (in seconds) the EC2 states should get fetched from AWS (5 seconds to 1 hour)",
    default: 10,
    min: 5,
    max: 3600,
    width: 4,
  },
];
